In [1]:
#1.Extract data from the given SalaryGender CSV file and store the data from each column in a separate NumPy array
import numpy as np
import csv

file_path = r"C:\Users\19899\OneDrive\Desktop\Python Course\SalaryGender.csv"

with open(file_path, mode='r') as file:
    csv_reader = csv.reader(file)
    
    next(csv_reader)
    
    column1 = [] 
    column2 = [] 
    column3 = []
    column4 = []

    for row in csv_reader:
        column1.append(float(row[0])) 
        column2.append(int(row[1]))  
        column3.append(int(row[2]))   
        column4.append(int(row[3]))  

column1 = np.array(column1)
column2 = np.array(column2)
column3 = np.array(column3)
column4 = np.array(column4)


print("Column 1:", column1)
print("Column 2:", column2)
print("Column 3:", column3)
print("Column 4:", column4)


Column 1: [140.    30.    35.1   30.    80.    30.    60.    31.1  125.    51.
   3.    46.   150.     3.   130.    15.   130.    84.   190.    74.
  73.    10.    50.     7.     9.5   15.2   28.6   20.    72.    81.
 100.    90.    90.    35.    30.    25.    52.     9.    63.    72.
  16.    92.   106.     2.5    9.    32.    32.    55.    52.    28.
  20.    14.7   22.3   34.8   84.    19.   160.    65.    55.     4.6
 102.    20.    62.    55.    45.6   40.    24.    35.    48.    20.
  40.7   15.     0.25 152.    39.8   12.    30.   120.     1.7   36.
  96.    38.    90.     9.    25.8   22.    38.8   72.    89.    41.
  89.    25.    52.   115.    66.    18.6  152.     1.8   35.     4.  ]
Column 2: [1 0 0 1 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0
 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1
 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0]
Column 3: [47 65 56 23 53 27 53 30 44 63 22 59 60 28 65 25 65 47 66 45 46 24 60 63

In [2]:
#2.Find: a. The number of men with a PhD b. The number of women with a PhD 

men_with_phd = 0
women_with_phd = 0

for index in range(len(column2)):
    if column2[index] == 1 and column4[index] == 1:  
        men_with_phd += 1
    elif column2[index] == 0 and column4[index] == 1:  
        women_with_phd += 1

print(f"men with a phd: {men_with_phd}")
print(f"women with a phd: {women_with_phd}")



men with a phd: 24
women with a phd: 15


In [ ]:
'''3. Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD from SalaryGender CSV file. '''
import pandas as pd
column1 = np.array(column1)
column2 = np.array(column2)
column3 = np.array(column3)
column4 = np.array(column4)

data = {'Age': column3, 'PhD': column4}
df = pd.DataFrame(data)


df_filtered = df[df['PhD'] == 1]

print("\nOnly PhD holders:")
print(df_filtered)

df_filtered.to_csv(file_path, index=False)



In [1]:
#4.Calculate the total number of people who have a PhD degree from SalaryGender CSV 

import pandas as pd


file_path = r"C:\Users\19899\OneDrive\Desktop\Python Course\SalaryGender.csv"
df = pd.read_csv(file_path)

phd_holders = df[df['PhD'] == 1]

total_phd_holders = phd_holders.shape[0]

print(f"Total number of people with a PhD: {total_phd_holders}")


Total number of people with a PhD: 39


In [2]:
#5. How do you Count The Number Of Times Each Value Appears In An Array Of Integers? 
 #

from collections import Counter

my_array = [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

# Use Counter to count occurrences
counts = Counter(my_array)

# Print the result
print(counts)


Counter({0: 4, 4: 3, 5: 2, 1: 2, 3: 1, 2: 1, 9: 1})


In [16]:
#6. Create a numpy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5. 
import numpy as np
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


filtered_elements = arr[arr > 5]

print(filtered_elements)



[ 6  7  8  9 10 11]


In [17]:
#7. Create a numpy array having NaN (Not a Number) and print it. 
import numpy as np

arr_with_nan = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])
print("Array with NaN values:")
print(arr_with_nan)

Array with NaN values:
[nan  1.  2. nan  3.  4.  5.]


In [ ]:
#8Create a 10x10 array with random values and find the minimum and maximum values
random_array = np.random.rand(10, 10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("\n10x10 Random Array:")
print(random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


In [5]:

#9.Create a random vector of size 30 and find the mean value.

#import numpy as np

random_vector = np.random.rand(30)


mean_value = np.mean(random_vector)

print("Mean value:", mean_value)



Mean value: 0.5090194989712399


In [7]:
#10. Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9 
import numpy as n
array = np.arange(11)
array[(array > 3) & (array < 9)] *= -1
print(array)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [11]:
#11. Create a random array of 3 rows and 3 columns and sort it according to 1st column, 2nd column or 3rd column. 
import numpy as np

random_array = np.random.randint(0,10,(3, 3))

sorted_by_column1 = random_array[random_array[:, 0].argsort()]
sorted_by_column2 = random_array[random_array[:, 1].argsort()]
sorted_by_column3 = random_array[random_array[:, 2].argsort()]

# Print results
print("Original array\n", random_array)
print("Sorted by 1st column", sorted_by_column1)
print("Sorted by 2nd column", sorted_by_column2)
print("Sorted by 3rd column", sorted_by_column3)


Original array
 [[5 4 7]
 [3 2 3]
 [5 6 2]]
Sorted by 1st column [[3 2 3]
 [5 4 7]
 [5 6 2]]
Sorted by 2nd column [[3 2 3]
 [5 4 7]
 [5 6 2]]
Sorted by 3rd column [[5 6 2]
 [3 2 3]
 [5 4 7]]


In [12]:
#12. Create a four dimensions array get sum over the last two axis at once.
import numpy as np
array_4d = np.random.randint(1, 10, size=(3, 4, 5, 6))
print("Original array:", array_4d.shape)
sum_of_axis = array_4d.sum(axis=(-2, -1))

print("Sum over the last two axes:")
print(sum_of_axis)
print( sum_of_axis.shape)


Original array: (3, 4, 5, 6)
Sum over the last two axes:
[[146 130 163 148]
 [146 158 142 152]
 [158 153 144 132]]
(3, 4)


In [ ]:

 #13. Create a random array and swap two rows of an array. 

array = np.random.randint(1, 10, size=(4, 4))
print("Original array:")
print(array)
array[[0, 2]] = array[[2, 0]]
print("\nArray after swapping rows 0 and 2:")
print(array)


In [13]:

#14. Create a random matrix and Compute a matrix rank.'''
import numpy as np
matrix = np.random.randint(1, 10, size=(3, 3))
print("Random matrix:")
print(matrix)
rank = np.linalg.matrix_rank(matrix)
print("Rank:", rank)


Random matrix:
[[7 4 8]
 [5 8 6]
 [1 9 5]]

Matrix rank: 3
